apiVersion: v1
kind: ReplicationController
metadata:
  name: ybethoulerc
spec:
  replicas: 3
  selector:
    app: ybethoulerc
  template:
    metadata:
      name: ybethoulerc
      labels:
        app: ybethoulerc
    spec:
      containers:
      - name: ybethoulerc
        image: gcr.io/project-staging1/ybethoule-rest-api:1.0
        ports:
        - containerPort: 80